name: Run SCM Discovery
 
on: [push, pull_request]
 
jobs:
 
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
     
    - name: Get current working directory
      run: pwd
    
        
    - name: Execute Bridge
      run: /Users/saraf/Downloads/synopsys-bridge-1-3/synopsys-bridge --input /Users/saraf/Downloads/ninjasworkout-master/input.json --stage polaris --diagnostics
